# 03. Pandas 이해 및 활용 ① DataFrame 살펴보기

**AICE Associate 학습 3단계**

pandas는 표 형태의 데이터를 다루는 라이브러리입니다. 시험의 **데이터 분석·전처리 영역(50점)** 은 거의 전부 pandas로 해결합니다.

### 학습 목표
1. Series와 DataFrame의 구조를 이해한다.
2. CSV 파일을 읽어 데이터의 크기, 컬럼, 자료형, 통계를 확인한다.
3. 원하는 행과 열을 선택하고(인덱싱), 조건으로 필터링하고, 정렬할 수 있다.

### 사용 데이터: `cust_data.csv` (통신사 고객 데이터, 학습용)
| 컬럼 | 설명 |
|---|---|
| class | 고객 등급 (A~H) |
| sex | 성별 (M/F) |
| age | 나이 |
| service | 가입 서비스 수 |
| stop | 일시정지 여부 (Y/N) |
| npay | 미납 여부 (Y/N) |
| avg_bill | 3개월 평균 청구 금액 |
| A_bill | A상품 청구 금액 |
| B_bill | B상품 청구 금액 |
| termination | 해지 여부 (Y/N) ← 예측 대상 |

In [1]:
import pandas as pd
import numpy as np

---
## 1. Series와 DataFrame

- **Series**: 인덱스가 붙은 1차원 데이터 (엑셀의 한 열)
- **DataFrame**: 여러 Series가 모인 2차원 표 (엑셀 시트)

In [2]:
s = pd.Series([90, 85, 77], index=['kim', 'lee', 'park'], name='score')
s

kim     90
lee     85
park    77
Name: score, dtype: int64

In [3]:
df_small = pd.DataFrame({
    'name': ['kim', 'lee', 'park', 'choi'],
    'age': [25, 32, 47, 51],
    'city': ['서울', '부산', '서울', '대구']
})
df_small

   name  age city
0   kim   25   서울
1   lee   32   부산
2  park   47   서울
3  choi   51   대구

In [4]:
# 리스트의 리스트로도 만들 수 있습니다
pd.DataFrame([[1, 'a'], [2, 'b']], columns=['num', 'char'])

   num char
0    1    a
1    2    b

---
## 2. 데이터 읽어오기: `pd.read_csv()`

- 시험에서는 csv 파일이 노트북과 **같은 경로**에 있으므로 `'./파일명.csv'` 또는 `'파일명.csv'`로 읽습니다.
- 한글이 포함된 파일이 `UnicodeDecodeError`를 일으키면 `encoding='cp949'` 를 지정합니다.

In [5]:
df = pd.read_csv('./cust_data.csv')
df.head()          # 처음 5행 (괄호 안에 숫자를 넣으면 그만큼)

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
0,B,F,61,2,N,N,7190.9881,3479.1102,2878.7129,N
1,E,M,55,1,N,Y,25045.0340,23940.8983,648.1402,N
2,D,M,29,4,N,Y,24942.9410,20637.5226,4894.4189,N
3,C,M,52,1,Y,N,15789.8007,15655.5138,0.0000,Y
4,C,M,22,2,N,N,9859.3532,7796.0435,1054.4661,N

In [6]:
df.tail(3)         # 마지막 3행

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
9927,D,M,62,3,N,N,31846.0094,24874.2897,6790.91,N
9928,D,M,42,1,N,N,18579.8106,18815.4247,0.00,N
9929,D,M,56,1,N,N,12511.3167,12216.7632,0.00,N

In [7]:
df.sample(3, random_state=42)   # 무작위 3행

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
2688,E,M,52,1,N,N,50352.3908,49880.1057,0.0000,N
4504,E,F,28,1,N,N,21891.8032,17091.3286,4467.1454,N
7136,C,M,19,1,N,Y,26510.1081,20439.6941,6261.7909,Y

---
## 3. 데이터 구조 파악하기

| 코드 | 결과 |
|---|---|
| `df.shape` | (행 수, 열 수) |
| `df.columns` | 컬럼 이름 목록 |
| `df.index` | 인덱스 |
| `df.dtypes` | 컬럼별 자료형 |
| `df.info()` | 행 수, 컬럼별 결측 아닌 값 개수, 자료형, 메모리 |
| `df.describe()` | 수치형 컬럼의 기초 통계 |

In [8]:
print(df.shape)
print(df.columns)
print(df.dtypes)

(9930, 10)
Index(['class', 'sex', 'age', 'service', 'stop', 'npay', 'avg_bill', 'A_bill',
       'B_bill', 'termination'],
      dtype='object')
class           object
sex             object
age              int64
service          int64
stop            object
npay            object
avg_bill       float64
A_bill         float64
B_bill         float64
termination     object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        9930 non-null   object
 1   sex          9930 non-null   object
 2   age          9930 non-null   int64
 3   service      9930 non-null   int64
 4   stop         9930 non-null   object
 5   npay         9930 non-null   object
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 775.9+ KB

> 📌 `info()` 결과에서 **Non-Null Count가 전체 행 수보다 작으면 결측치**가 있다는 뜻입니다.
> `object` 자료형은 문자열이며, 머신러닝 모델에 넣기 전에 숫자로 바꿔야 합니다 (원-핫 인코딩 등).

In [10]:
df.describe()

               age      service      avg_bill        A_bill        B_bill
count  9930.000000  9930.000000   9930.000000   9930.000000   9930.000000
mean     45.103122     1.909466  20949.876731  17821.727136   3121.128966
std      12.745802     1.060826   9655.922058   8909.685660   3649.589256
min      18.000000     1.000000   1000.000000    239.540500      0.000000
25%      36.000000     1.000000  14079.621625  11459.432425      0.000000
50%      45.000000     2.000000  19511.670050  16369.316400   2063.190900
75%      54.000000     2.000000  26160.586025  22501.554500   4815.524275
max      90.000000     5.000000  80338.109100  78029.595700  36790.799400

In [11]:
# 문자형 컬럼의 요약 (개수, 고유값 수, 최빈값, 최빈값 빈도)
df.describe(include='object')

       class   sex  stop  npay termination
count   9930  9930  9930  9930        9930
unique     8     2     2     2           2
top        D     M     N     N           N
freq    2167  5531  9117  8420        8116

In [12]:
# 전치(T)하면 컬럼이 많을 때 보기 편합니다
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,9930.0,45.103122,12.745802,18.0000,36.000000,45.00000,54.000000,90.0000
service,9930.0,1.909466,1.060826,1.0000,1.000000,2.00000,2.000000,5.0000
avg_bill,9930.0,20949.876731,9655.922058,1000.0000,14079.621625,19511.67005,26160.586025,80338.1091
A_bill,9930.0,17821.727136,8909.685660,239.5405,11459.432425,16369.31640,22501.554500,78029.5957
B_bill,9930.0,3121.128966,3649.589256,0.0000,0.000000,2063.19090,4815.524275,36790.7994

---
## 4. 값의 분포 확인하기

In [13]:
df['termination'].value_counts()             # 값별 개수

termination
N    8116
Y    1814
Name: count, dtype: int64

In [14]:
df['termination'].value_counts(normalize=True)   # 비율

termination
N    0.817321
Y    0.182679
Name: proportion, dtype: float64

In [15]:
print(df['class'].unique())     # 고유값 목록
print(df['class'].nunique())    # 고유값 개수
df.nunique()                    # 모든 컬럼의 고유값 개수

['B' 'E' 'D' 'C' 'F' 'G' 'H' 'A']
8

class             8
sex               2
age              72
service           5
stop              2
npay              2
avg_bill       9927
A_bill         9930
B_bill         6969
termination       2
dtype: int64

In [16]:
# 기초 통계 함수
print(df['age'].mean(), df['age'].median(), df['age'].std())
print(df['age'].min(), df['age'].max())
print(df['avg_bill'].quantile(0.25), df['avg_bill'].quantile(0.75))   # 사분위수 (이상치 처리에 사용!)

45.103121852970794 45.0 12.745802218338305
18 90
14079.621625 26160.586025

In [17]:
# 수치형 컬럼 간 상관계수
df.corr(numeric_only=True)

               age   service  avg_bill    A_bill    B_bill
age       1.000000  0.007126 -0.006820 -0.004761 -0.006718
service   0.007126  1.000000  0.021435  0.023785 -0.001168
avg_bill -0.006820  0.021435  1.000000  0.923670  0.380161
A_bill   -0.004761  0.023785  0.923670  1.000000  0.002301
B_bill   -0.006718 -0.001168  0.380161  0.002301  1.000000

---
## 5. 컬럼 선택하기

- 1개 컬럼: `df['col']` → **Series**
- 여러 컬럼: `df[['col1', 'col2']]` → **DataFrame** (대괄호 두 겹!)

In [18]:
df['age'].head(3)

0    61
1    55
2    29
Name: age, dtype: int64

In [19]:
df[['class', 'age', 'termination']].head(3)

  class  age termination
0     B   61           N
1     E   55           N
2     D   29           N

In [20]:
# 자료형으로 컬럼 고르기
df.select_dtypes(include='object').columns

Index(['class', 'sex', 'stop', 'npay', 'termination'], dtype='object')

In [21]:
df.select_dtypes(include='number').columns

Index(['age', 'service', 'avg_bill', 'A_bill', 'B_bill'], dtype='object')

---
## 6. 행 선택하기: `loc` vs `iloc`

| | `loc` | `iloc` |
|---|---|---|
| 기준 | 인덱스 **이름(label)** | 인덱스 **위치(정수)** |
| 슬라이싱 끝 | **포함** | 미포함 |
| 예 | `df.loc[0:2, 'age']` | `df.iloc[0:2, 2]` |

In [22]:
df.loc[0:2, ['class', 'age']]     # 0, 1, 2행 (끝 포함)

  class  age
0     B   61
1     E   55
2     D   29

In [23]:
df.iloc[0:2, 0:3]                 # 0, 1행 / 0~2열 (끝 미포함)

  class sex  age
0     B   F   61
1     E   M   55

In [24]:
df.iloc[-1]                       # 마지막 행

class                   D
sex                     M
age                    56
service                 1
stop                    N
npay                    N
avg_bill       12511.3167
A_bill         12216.7632
B_bill                0.0
termination             N
Name: 9929, dtype: object

In [25]:
df.loc[5, 'avg_bill']             # 특정 셀 하나

np.float64(25856.9365)

---
## 7. 조건으로 필터링하기 (Boolean Indexing)

- 조건식은 True/False로 이루어진 Series를 만듭니다. 이를 `df[ ]` 에 넣으면 True인 행만 남습니다.
- 여러 조건: `&`(and), `|`(or), `~`(not) + **각 조건을 괄호로 감싸기**

In [26]:
cond = df['age'] >= 60
cond.head()

0     True
1    False
2    False
3    False
4    False
Name: age, dtype: bool

In [27]:
df[cond].head()

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
0,B,F,61,2,N,N,7190.9881,3479.1102,2878.7129,N
12,E,M,64,1,N,N,15685.1881,9317.6091,6429.5864,N
21,D,F,73,4,N,N,31273.1968,31260.2583,0.0000,N
23,A,M,63,4,N,N,7825.3586,7867.7980,0.0000,N
24,D,F,62,1,N,N,20757.9706,20475.2040,281.2378,N

In [28]:
# 60세 이상이면서 해지한 고객
df[(df['age'] >= 60) & (df['termination'] == 'Y')].shape

(210, 10)

In [29]:
# 미납이거나 일시정지한 고객
df[(df['npay'] == 'Y') | (df['stop'] == 'Y')].shape

(2214, 10)

In [30]:
# isin: 여러 값 중 하나에 해당
df[df['class'].isin(['A', 'B'])].head(3)

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
0,B,F,61,2,N,N,7190.9881,3479.1102,2878.7129,N
7,B,M,57,2,N,N,7176.8383,7136.4475,370.4726,N
23,A,M,63,4,N,N,7825.3586,7867.7980,0.0000,N

In [31]:
# ~ : 조건 반대
df[~df['class'].isin(['A', 'B'])]['class'].unique()

array(['E', 'D', 'C', 'F', 'G', 'H'], dtype=object)

In [32]:
# between: 범위
df[df['age'].between(30, 39)].shape

(2199, 10)

In [33]:
# query: 문자열로 조건 작성
df.query("age >= 60 and termination == 'Y'").shape

(210, 10)

In [34]:
# loc에 조건과 컬럼을 함께
df.loc[df['avg_bill'] > 50000, ['class', 'avg_bill']].head()

    class    avg_bill
94      E  58755.6132
115     A  60489.3279
389     B  51984.2484
466     D  54922.8920
514     D  58165.5785

---
## 8. 정렬하기

- 값 기준: `sort_values('컬럼', ascending=False)`
- 인덱스 기준: `sort_index()`

> ⚠️ 샘플 문항 11번에서 `sort_index('importance', ...)` 를 `sort_values('importance', ...)` 로 고치는 문제가 나왔습니다. 두 함수를 꼭 구분하세요.

In [35]:
df.sort_values('avg_bill', ascending=False).head()

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
9869,H,M,41,5,N,N,80338.1091,75028.7876,5306.5224,N
771,E,M,30,3,N,N,77518.7582,78029.5957,0.0000,N
6058,G,M,65,4,N,Y,75890.4605,74169.5021,1912.7314,N
8163,D,F,46,3,N,N,72457.2676,67297.5827,5371.5552,N
8559,E,M,47,3,N,N,71491.9252,59245.2002,12159.7270,N

In [36]:
df.sort_values(['class', 'age'], ascending=[True, False]).head()

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
3265,A,F,85,1,Y,N,28959.5380,27312.4256,2203.9644,Y
3457,A,M,84,2,N,N,15795.7801,15474.5282,0.0000,N
2767,A,M,80,2,N,N,16604.1740,16457.2145,0.0000,N
9388,A,M,80,1,N,N,13647.8953,10080.7522,3887.7320,N
6904,A,M,79,1,N,N,8826.5179,4476.3265,4731.3531,N

In [37]:
df.nlargest(3, 'avg_bill')

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
9869,H,M,41,5,N,N,80338.1091,75028.7876,5306.5224,N
771,E,M,30,3,N,N,77518.7582,78029.5957,0.0000,N
6058,G,M,65,4,N,Y,75890.4605,74169.5021,1912.7314,N

---
## 9. 간단한 그룹 통계 미리보기

다음 노트북에서 자세히 다루지만, `groupby`는 매우 자주 쓰입니다.

In [38]:
df.groupby('termination')['avg_bill'].mean()

termination
N    21513.753559
Y    18427.040822
Name: avg_bill, dtype: float64

In [39]:
df.groupby('class')['termination'].value_counts(normalize=True).unstack().round(3)

termination      N      Y
class
A            0.825  0.175
B            0.825  0.175
C            0.834  0.166
D            0.819  0.181
E            0.817  0.183
F            0.816  0.184
G            0.765  0.235
H            0.795  0.205

---
## 10. 다른 데이터로 연습: Titanic

In [40]:
titanic = pd.read_csv('titanic.csv')
print(titanic.shape)
titanic.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

---
## ✏️ 연습문제 (titanic.csv 사용)

**문제 1.** `titanic.csv`를 읽어 `titanic` 변수에 저장하고 처음 4개 행을 출력하세요.

In [42]:
# 여기에 답안코드를 작성하고 실행하세요.

**문제 2.** `Age` 컬럼에 결측치가 아닌 값이 몇 개인지 `info()`로 확인하고, 그 개수를 `답안2` 변수에 저장하세요.

In [43]:
# 여기에 답안코드를 작성하고 실행하세요.

**문제 3.** 생존(`Survived`)한 승객의 비율을 구하고, 소수점 셋째 자리에서 반올림하여 `답안3` 변수에 저장하세요.

In [44]:
# 여기에 답안코드를 작성하고 실행하세요.

**문제 4.** 1등석(`Pclass == 1`)이면서 여성(`Sex == 'female'`)인 승객의 수를 `답안4` 변수에 저장하세요.

In [45]:
# 여기에 답안코드를 작성하고 실행하세요.

**문제 5.** 운임(`Fare`)이 가장 비싼 승객 3명의 `Name`, `Pclass`, `Fare` 컬럼을 출력하세요.

In [46]:
# 여기에 답안코드를 작성하고 실행하세요.

**문제 6.** 아래 코드의 오류를 정정하세요. (승선항 `Embarked`가 'S' 또는 'C'이고 나이가 30세 미만인 승객 수)
```python
titanic[titanic['Embarked'].isin('S', 'C') and titanic['Age'] < 30].shape[0]
```

In [47]:
# 아래의 코드를 정정하고 실행하세요.

---
## ✅ 정답 및 해설

In [48]:
# 문제 1
titanic = pd.read_csv('./titanic.csv')
titanic.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [49]:
# 문제 2
titanic.info()
답안2 = 714
print(답안2, titanic['Age'].notnull().sum())   # 코드로도 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
714 714

In [50]:
# 문제 3
답안3 = round(titanic['Survived'].mean(), 3)       # 0/1 컬럼의 평균 = 1의 비율
print(답안3)
print(titanic['Survived'].value_counts(normalize=True))

0.384
Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [51]:
# 문제 4
답안4 = titanic[(titanic['Pclass'] == 1) & (titanic['Sex'] == 'female')].shape[0]
print(답안4)

94

In [52]:
# 문제 5
titanic.sort_values('Fare', ascending=False)[['Name', 'Pclass', 'Fare']].head(3)

                                   Name  Pclass      Fare
737              Lesurer, Mr. Gustave J       1  512.3292
679  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
258                    Ward, Miss. Anna       1  512.3292

In [53]:
# 문제 6 : isin 은 리스트를 받아야 하고, and 대신 &, 각 조건은 괄호로
titanic[(titanic['Embarked'].isin(['S', 'C'])) & (titanic['Age'] < 30)].shape[0]

369